# Generated by Django 3.0.7 on 2020-06-11 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=55)),
                ('isFollowedUp', models.BooleanField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=55)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('isContacted', models.BooleanField(max_length=55, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewDate', models.DateField()),
                ('notes', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Employee')),
                ('interviewType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.InterviewType')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Seeker'),
        ),
    ]
