# Generated by Django 3.0.7 on 2020-06-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isDeleted',
            field=models.BooleanField(null=True),
        ),
    ]
