# Generated by Django 3.0.7 on 2020-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0003_remove_company_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
