# Generated by Django 3.0.7 on 2020-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0004_company_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
