# Generated by Django 3.0.7 on 2020-06-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0005_employee_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Employee'),
        ),
    ]
