# Generated by Django 3.0.7 on 2020-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0006_auto_20200612_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewDate',
            field=models.DateTimeField(),
        ),
    ]
