# Generated by Django 3.0.7 on 2020-06-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0008_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seekerapp.Seeker'),
        ),
    ]
